(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(c-basic-offset 2)
 '(c-default-style '((java-mode . "gnu")))
 '(c-insert-tab-function 'insert-tab)
 '(c-offsets-alist
   '((inline-open . 0)
     (inline-close . 0)
     (block-open . 0)
     (block-close . 0)
     (topmost-intro . 0)
     (inclass . +)
     (member-init-intro . +)
     (substatement-open . 0)
     (statement-block-intro . +)
     (func-decl-cont . 0)
     (defun-block-intro . +)
     (c-lineup-C-comments . 1)))
 '(company-abort-manual-when-too-short t)
 '(company-auto-complete nil)
 '(company-box-color-icon t)
 '(company-box-enable-icon nil)
 '(company-dict-dir "~/.emacs.d/company-dict/")
 '(company-dict-minor-mode-list '(yas-minor-mode))
 '(company-mode 1 t)
 '(company-show-numbers t)
 '(company-tooltip-flip-when-above t)
 '(company-tooltip-idle-delay nil)
 '(company-tooltip-margin 2)
 '(company-tooltip-offset-display 'lines)
 '(compilation-ask-about-save nil)
 '(compilation-scroll-output t)
 '(css-indent-offset 2)
 '(cssm-indent-level 1 t)
 '(global-company-mode t)
 '(global-hl-todo-mode t)
 '(global-semantic-decoration-mode t)
 '(global-semantic-highlight-edits-mode t)
 '(global-semantic-highlight-func-mode t)
 '(global-semantic-idle-breadcrumbs-mode t nil (semantic/idle))
 '(global-semantic-idle-completions-mode t nil (semantic/idle))
 '(global-semantic-idle-local-symbol-highlight-mode t nil (semantic/idle))
 '(global-semantic-idle-summary-mode t)
 '(global-semantic-mru-bookmark-mode t)
 '(global-semantic-show-parser-state-mode t)
 '(global-semantic-show-unmatched-syntax-mode t)
 '(global-semantic-stickyfunc-mode t)
 '(global-whitespace-newline-mode t)
 '(groovy-indent-offset 2)
 '(highlight-indent-guides-character 124)
 '(highlight-indent-guides-method 'character)
 '(ido-mode nil)
 '(jdecomp-decompiler-paths
   '((cfr . "~/src/dependencies/cfr/cfr_0_132.jar")
     (procyon . "/usr/bin/procyon")) t)
 '(jdibug-connect-hosts '("127.0.0.1:6001"))
 '(js-indent-level 2 t)
 '(js2-bounce-indent-p nil t)
 '(js2-concat-multiline-strings nil t)
 '(js2-highlight-level 3 t)
 '(js2-include-jslint-globals t t)
 '(js2-include-node-externs t t)
 '(js2-mode-assume-strict t t)
 '(js2-skip-preprocessor-directives t t)
 '(kotlin-tab-width 2 t)
 '(multi-term-program "/bin/bash" t)
 '(neo-window-fixed-size nil)
 '(neo-window-width 35)
 '(nodejs-repl-command "node")
 '(org-agenda-files '("~/src/doc/todo.org"))
 '(org-highlight-latex-and-related '(latex script entities))
 '(org-priority-faces nil)
 '(org-src-preserve-indentation t)
 '(projectile-enable-caching t)
 '(projectile-indexing-method 'native)
 '(projectile-keymap-prefix "p")
 '(semantic-analyze-summary-function 'semantic-format-tag-short-doc)
 '(semantic-complete-inline-analyzer-displayor-class 'semantic-displayor-tooltip)
 '(semantic-complete-inline-analyzer-idle-displayor-class 'semantic-displayor-tooltip)
 '(semantic-decoration-mode nil t)
 '(semantic-decoration-styles
   '(("semantic-decoration-on-includes")
     ("semantic-decoration-on-protected-members")
     ("semantic-decoration-on-private-members")
     ("semantic-tag-boundary")))
 '(semantic-default-submodes
   '())
 '(semantic-displayor-tooltip-mode 'verbose)
 '(semantic-mode-line-prefix "SEM" nil (semantic/util-modes))
 '(semantic-sb-autoexpand-length 2 t)
 '(semantic-show-unmatched-syntax-mode nil t)
 '(senator-highlight-found t)
 '(senator-step-at-start-end-tag-classes nil)
 '(web-mode-attr-value-indent-offset nil t)
 '(web-mode-enable-auto-closing t t)
 '(web-mode-enable-auto-pairing t t)
 '(web-mode-enable-auto-quoting t t)
 '(web-mode-enable-current-column-highlight nil t)
 '(web-mode-enable-current-element-highlight t t)
 '(web-mode-enable-element-tag-fontification t t)
 '(web-mode-enable-html-entities-fontification t t)
 '(web-mode-indent-style 2 t)
 '(web-mode-markup-indent-offset 2 t)
 '(web-mode-script-padding 0 t)
 '(whitespace-modes '(awk-mode) t)
 '(yas-prompt-functions '(yas-dropdown-prompt yas-completing-prompt yas-no-prompt)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-preview ((t (:background "RoyalBlue4" :foreground "gray97"))))
 '(company-preview-search ((t (:inherit company-preview :foreground "light green"))))
 '(company-template-field ((t (:background "cyan4" :foreground "yellow3"))))
 '(company-tooltip ((t (:background "grey20" :foreground "white"))))
 '(jdibug-breakpoint-disabled ((t (:background "green" :foreground "black"))))
 '(jdibug-breakpoint-enabled ((t (:background "red" :foreground "white"))))
 '(jdibug-breakpoint-unresolved ((t (:background "yellow" :foreground "black"))))
 '(jdibug-current-frame ((t (:background "blue" :foreground "white"))))
 '(jdibug-current-line ((t (:background "black" :foreground "red"))))
 '(js2-function-call ((t (:underline t))))
 '(js2-object-property ((t (:foreground "LightSalmon3"))))
 '(markup-anchor-face ((t (:inherit grey :overline t))))
 '(markup-attribute-face ((t (:foreground "purple"))))
 '(markup-command-face ((t (:foreground "white" :weight bold))))
 '(markup-complex-replacement-face ((t (:background "blue" :foreground "white"))))
 '(markup-internal-reference-face ((t (:foreground "green" :weight bold))))
 '(markup-list-face ((t (:inherit markup-meta-face :foreground "plum1" :weight bold))))
 '(markup-meta-face ((t (:foreground "blue" :weight thin))))
 '(markup-table-cell-face ((t (:inherit markup-table-face :background "blue" :foreground "yellow" :weight bold))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "pink3"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "PaleGreen3"))))
 '(web-mode-current-element-highlight-face ((t (:foreground "#ff" :underline t))))
 '(web-mode-doctype-face ((t (:distant-foreground "#ff" :foreground "#ff"))))
 '(whitespace-empty ((t (:foreground "DodgerBlue4"))))
 '(whitespace-indentation ((t (:foreground "DodgerBlue4"))))
 '(whitespace-line ((t nil)))
 '(whitespace-newline ((t (:foreground "dark slate gray"))))
 '(whitespace-space ((t (:foreground "DodgerBlue4"))))
 '(whitespace-space-after-tab ((t (:foreground "white"))))
 '(whitespace-space-before-tab ((t (:background "white" :foreground "blue")))))
