(setq newsticker-url-list
      '(
        ("Github: xxtjaxx watchlist" "http://gitorious.org/~xxtjaxx/watchlist.atom" nil nil nil)
        ("Github: Steffens github" "http://github.com/sbruchmann.atom" nil nil nil)
        ("Linux Community" "http://www.linux-community.de/rss/feed/main" nil nil nil)
        ("Coding Horror" "http://feeds.feedburner.com/codinghorror" nil nil nil)
        ("Credativ" "http://blog.credativ.com/feed/" nil nil nil)
        ("[a-z]*" "http://denever.blogspot.com/feeds/posts/default" nil nil nil)
        ("Linux Outlaws" "http://feeds.feedburner.com/linuxoutlaws" nil nil nil)
        ("Dayo" "http://roneyworld.wordpress.com/feed/" nil nil nil)
        ("kryogenix" "http://feeds.feedburner.com/kryogenix" nil nil nil)
        ("T00nhole" "http://www.toonhole.com/feed/" nil nil nil)
        ("snippets RSS" "http://xxtjaxx.homelinux.net/snippet/index.rss" nil nil nil)
        ("snippet Atom" "http://xxtjaxx.homelinux.net/snippet/index.atom" nil nil nil)
        ("Planet Debian" "http://planet.debian.org/rss20.xml" nil nil nil)
        ("Planet Debian Admin" "http://planet.debian-administration.org/rss20.xml" nil nil nil)
        ("Liquidat" "http://liquidat.wordpress.com/feed/" nil nil nil)
        )
      )
