(defun other-window-back ()
  ( interactive )
  (other-window -1))

;; (defun xxtjaxx/browse-url-at-point ()
;;   (if ( word-at-point)

;;       )
;;   )
;--------Keyboardz-----------------------------------------------------
(keydef "C-x t" (multi-term) )
;; Stop myself from accidental insertion
(global-unset-key (kbd "C-x i"))

;; (keydef "C-x g" (w3m-search "google" (read-from-minibuffer "Google:")))
;; (keydef "C-c b" (w3m-browse-url (read-from-minibuffer "URL:")))
;; (keydef "C-x ^" (enlarge-window 5))
;; (keydef "C-x °" (enlarge-window -5))
;; (keydef "C-x <C-up>" (mocp-volume-up))
;; (keydef "C-x <C-down>" (mocp-volume-down))
;; (keydef "C-c d" (find-deb-package))
;; ;;(keydef "C-x C-b" xxtjaxx/browse-url-at-point)
;; (keydef "C-x C-b" browse-url-at-point)
;; (keydef "C-c c c" byte-compile-current-file)
;; (keydef "C-x h" (enlarge-window 1 t))
;; (keydef "C-x z" (enlarge-window -1 t))
;; (global-set-key "\C-xw" 'wget)
;; (global-set-key [f11] 'toggle-fullscreen)
;; (keydef "C-x o" 'other-window)
;; (keydef "C-x p" 'other-window-back)
;; (keydef "C-c C-x i" 'indent-region)
;; (keydef "C-x e" 'org-export-as-pdf)
;; (keydef "<XF86Back>" 'previous-buffer)
;; (keydef "<XF86Forward>" 'next-buffer)
;; (keydef "C-x |" 'split-window-right)
;; (global-set-key (kbd "ESC <left>") 'shrink-window-horizontally)
;; (global-set-key (kbd "ESC <right>") 'enlarge-window-horizontally)
;; (global-set-key (kbd "ESC <down>") 'shrink-window)
;; (global-set-key (kbd "ESC <up>") 'enlarge-window)
;----------------------------------------------------------------------
